language: java
env:
  - PLAY_VERSION=2.2.1
before_script:
  - cp conf/application.conf.example conf/application.conf
  - psql -c 'create database shace;' -U postgres
  - psql -c 'ALTER USER postgres WITH PASSWORD "postgres"' -U postgres
  - wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip

script:
  - play-${PLAY_VERSION}/play test
  - play-${PLAY_VERSION}/play compile