language: java
env:
  - PLAY_VERSION=2.2.1 MEDIA_PATH=`pwd`/public/media/ MEDIA_ROOT_URL="localhost" DB_DRIVER="org.postgresql.Driver" DATABASE_URL="postgresql://postgres@localhost:5432/shace" SECRET_KEY="8mtC^A9087655789^%$7890PO:Lp;'LmkUltiEx"
before_script:
  - psql -c 'create database shace;' -U postgres
  - wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip

script:
  - play-${PLAY_VERSION}/play test
  - play-${PLAY_VERSION}/play compile
  - sbt coveralls
